spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quartz-poc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp.use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        ddl-auto: validate
        enable_lazy_load_no_trans: true
    hikari:
      maximumPoolSize: 10
      minimumIdle: 3
      idleTimeout: 30000
